---

- hosts: virt:&kvm
  roles:
    - name: infra/virtualization/libvirt
      become: true
  tasks:
    - name: ensure permissions unchecked for tf storage
      become: true
      ansible.builtin.lineinfile:
        path: /etc/libvirt/qemu.conf
        regexp: "^#security_driver = .*$"
        line: 'security_driver = "none"'
      notify: restart libvirtd

  handlers:
    - name: restart libvirtd
      become: true
      ansible.builtin.systemd_service:
        name: libvirtd.service
        state: restarted

- hosts: virt:&lxd
  roles:
    - name: infra/virtualization/lxd

- hosts: virt:&docker
  roles:
    - role: infra/virtualization/docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_env.USER }}"

# - hosts: virt
#   gather_facts: false
#   roles:
#     - role: os/users
#       vars:
#         users_require_superuser: false
#         users_list:
#           - name: provisioner
#             groups:
#               - libvirt
