---

- hosts: all
  become: true
  gather_facts: false
  vars:
    upgrade_allow_reboot: false
  tasks:
    - name: apt
      block:
      - name: apt | update cache
        apt:
          update_cache: true
          force_apt_get: true
          cache_valid_time: 3600

      - name: apt | upgrade
        apt:
          upgrade: safe
          force_apt_get: true

      - name: apt | cleanup
        apt:
          autoremove: true
          purge: true

      - name: reboot | check if required
        register: reboot_required_file
        stat:
          path: /var/run/reboot-required
          get_md5: false

      - name: reboot
        when:
          - is_reboot_allowed
          - reboot_required_file.stat.exists
        reboot:
          msg: "Reboot initiated by Ansible for kernel updates"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
