---

- import_playbook: ./bootstrap.yaml

- hosts: all
  gather_facts: true 
  pre_tasks:
    - name: inventory hostname
      become: true
      hostname:
        name: "{{ inventory_hostname }}"
  roles:
    - role: os/users
    - role: os/openssh

- import_playbook: ./hw.yaml

- import_playbook: ./user/applications.yaml

- import_playbook: ./system/optimize.yaml

- import_playbook: ./system/upgrade.yaml

