--- 

- hosts: workstation
  environment: "{{ env | default({}) }}"
  tasks:
    - name: establish the local machine name and group
      add_host:
        hostname: "{{ inventory_hostname }}"
        groups:
          - hw
          - applications
        ansible_connection: "{{ ansible_connection }}"
      tags: always

- import_playbook: os/bootstrap.yml
  tags:
    - init
    - bootstrap

- import_playbook: os/system/minimal.yaml
  tags:
    - init
    - users
    - ssh

- import_playbook: os/hw.yaml
  tags:
    - init
    - hw

- import_playbook: virt/all.yaml
  tags: virt

# user
- import_playbook: os/user/applications.yml
  tags:
    - workstation
    - apps

- import_playbook: os/user/configurations.yml
  tags:
    - workstation 
    - configs

# services
- import_playbook: services/ntp.yml
  tags: 
    - service
    - ntp

- import_playbook: services/dns.yml
  tags:
    - service
    - dns

- import_playbook: services/nfs.yml
  tags:
    - service
    - nfs

